# Generated by Django 5.2.4 on 2025-07-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='creationDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
